spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_student3?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    password: root
    username: root
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
server:
  port: 8887


#·ÖÒ³²å¼þ
pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: true
  support-methods-arguments: true





